### ISSUE TITLE
UIPageViewController compatibility

### ISSUE THREAD

**Issue by proxi** [evadne/RAPageViewController#2]
I am using RAPageViewController as UIPageViewController replacement for targetting iOS5.0. It does work. However, there are some issues that prevent it from being used same way as Apple's controller. I reimplemented Apple's [PhotoScroller](http://developer.apple.com/library/ios/#samplecode/PhotoScroller) sample with it and added some logging: [RAPhotoScroller](https://github.com/proxi/RAPhotoScroller).

There are two obvious issues with the current implementation visible in the sample app:
- vc containment does not work properly. After scrolling two sample's 3rd page view controller has no children:
  `2013-01-15 15:20:49.641 PhotoScroll[36851:707] children: (null)`
- scrolling past 3rd page crashes at RAPageViewController line 144 (because there are only 3 pages currentViewController is nil):
  `_viewControllers = @[ self.currentPageViewController ];`

I did some refactoring that fixes both issues. I'm working on a patch.

**Comment by evadne** [comment]
Hey, thanks for the message. Have you got the patch up anywhere?

I’m closing this issue to track iOS 5.0 compatibility under https://github.com/evadne/RAPageViewController/issues/5. Thanks so much.

**Comment by proxi** [comment]
Sorry, I didn't follow with the patch, but instead did some modifications for my project. Here's what I did: https://gist.github.com/proxi/5382263
